import { House1, House2, House3, House4, House5, House6 } from '../../../assets/images/index.img'

const Listings = [
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House1,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House2,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House3,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House4,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House5,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 101,
        alpha: 'zz',
        name: 'John XXX',
        date: '10-11-202283987587389573',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House6,
        description: 'modern flats and appartments',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
]
export default Listings;