import { House1, House2, House3, House4, House5, House6 } from '../../assets/images/index.img'

const Listings = [
    {
        id: 1,
        alpha: 'J',
        name: 'John Doe',
        date: '10-11-2022',
        totalNumberOfImages: 4,
        type: 'house',
        category: 'sale',
        save: 'save',
        image: House1,
        description: 'lands for sale',
        location: 'Sangotedo, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        size: 750,
    },
    {
        id: 2,
        alpha: 'M',
        name: 'Kennedy Jay',
        date: '3-8-2023',
        totalNumberOfImages: 3,
        type: 'house',
        category: 'sale',
        image: House2,
        description: 'houses for sale and rent',
        location: 'Badore, Ajah, Lagos',
        numberOfBedrooms: 2,
        numberOfBathrooms: 4,
        size: 300,
    },
    {
        id: 3,
        alpha: 'K',
        name: 'Shun Michael',
        date: '13-5-2024',
        totalNumberOfImages: 5,
        type: 'house',
        category: 'sale',
        image: House3,
        description: 'cars for sale and hire',
        location: 'Ibeju-Epe, Ajah, Lagos',
        numberOfBedrooms: 2,
        numberOfBathrooms: 2,
        size: 600,
    },
    {
        id: 4,
        alpha: 'P',
        name: 'Queen Friday',
        date: '4-7-2022',
        totalNumberOfImages: 1,
        type: 'house',
        category: 'sale',
        image: House4,
        description: 'shortlets',
        location: 'Lekki-gardens, Ajah, Lagos',
        numberOfBedrooms: 1,
        numberOfBathrooms: 1,
        size: 330,
    },
    {
        id: 5,
        alpha: 'A',
        name: 'Jeffery Kent',
        date: '13-5-2024',
        totalNumberOfImages: 3,
        type: 'house',
        category: 'sale',
        image: House5,
        description: 'office-spaces and shops',
        location: 'Ogidan, Ajah, Lagos',
        numberOfBedrooms: 1,
        numberOfBathrooms: 2,
        size: 530,
    },
    {
        id: 6,
        alpha: 'M',
        name: 'Jackie Shan',
        date: '3-15-2022',
        totalNumberOfImages: 2,
        type: 'house',
        category: 'sale',
        image: House6,
        description: 'other properties',
        location: 'Ibeju-Epe, Ajah, Lagos',
        numberOfBedrooms: 3,
        numberOfBathrooms: 3,
        size: 435,
    },
]
export default Listings;